version: 2.1
jobs:
  build:
    docker:
      - image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Compile and Run Code
          command: |
            gcc main.c -o main
            ./main
