version: 2.1
jobs:
  build:
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Compile and Run Code
          command: |
            gcc helloWorld.c -o helloWorld
            ./helloWorld
