# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1 ##Versao utilizada.

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello: ##JOB chamado "say-hello". Nesse caso, este job não pertence a um workflow exclusivo.
  
    docker: ##Especificando o ambiente de execução no docker. 
      - image: cimg/base:stable #A imagem base utilizada no docker, sendo esta bastante comum no CircleCI

    steps: #Etapas executando comandos.
      - checkout #Realiza o checkout do código fonte no repositório---
                    #---garantindo que o circleCI utiliza a versão atualizada do repositório.
      - run:      #Realiza o comando abaixo. Nesse caso, realiza o famoso "Hello, World!", no OS do docker.
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows: #Um workflow. Jobs podem tanto estar "dentro" de workflows, quanto fora. 
  say-hello-workflow: #Neste workflow, o job "global" chamado "say-hello" é chamado.
    jobs:
      - say-hello
      #Aqui poderiamos incluir jobs que realizam testes, por exemplo. 
      #Ao incluir testes aqui, torna-se automatizada a etapa de testes.
      #O ideal é executar o teste primeiro. Caso ele seja bem sucedido, executar o próximo job "say-hello"
